# ANN Practical Implementation (Churn Prediction)

In the previous notebook, we learned about **Vanishing Gradient, Dropout, Optimizers, and Loss Functions.**\ 

Today, we will apply those concepts in practice using an Artificial Neural Network (ANN) to predict customer churn.
Dataset: Churn_Modelling.csv

## Importing Libraries

In [97]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [98]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [99]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [100]:
import pandas as pd
import numpy as np
import tensorflow as tf


# Data Preprocessing

1.Import dataset\
2.Separate features (X) and target (y)\
3.Encode categorical variables (Gender, Geography)\
4.Perform Feature Scaling\
5.Split into training & test sets

In [101]:
dataset = pd.read_csv(r'C:\Ds & AI ( my work)\Deep_Learning\ANN\Churn_Modelling.csv')

In [102]:
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [103]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0


# Encoding Categorical Data

- Label Encoding for Gender
- OneHot Encoding for Geography

In [104]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [105]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [106]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [107]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]],
      shape=(10000, 12), dtype=object)

# Feature Scaling

In [108]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [109]:
x

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 12))

# Splitting Dataset

In [110]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.20, random_state=0)

In [111]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)


# ANN MODEL BUILDING ARCHITECTURE

In [112]:
ann = tf.keras.models.Sequential()      # establish layer one after another

## Adding Input Layer - Hidden Layers and Output Layer

In [113]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu')) # input layer
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu')) # hidden layer 1
ann.add(tf.keras.layers.Dense(units = 5,activation = 'relu'))  # hidden layer 2 
ann.add(tf.keras.layers.Dense(units = 4,activation = 'relu')) # hidden layer 3
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid')) # output layer 

In [114]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [115]:
ann.fit(x_train,y_train,batch_size = 32,epochs = 150,validation_data=(x_test,y_test))

Epoch 1/150


250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7847 - loss: 0.5483 - val_accuracy: 0.7975 - val_loss: 0.4777
Epoch 2/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7960 - loss: 0.4614 - val_accuracy: 0.7975 - val_loss: 0.4488
Epoch 3/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7960 - loss: 0.4417 - val_accuracy: 0.7975 - val_loss: 0.4334
Epoch 4/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7960 - loss: 0.4328 - val_accuracy: 0.7975 - val_loss: 0.4283
Epoch 5/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7995 - loss: 0.4282 - val_accuracy: 0.8125 - val_loss: 0.4244
Epoch 6/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8133 - loss: 0.4249 - val_accuracy: 0.8160 - val_loss: 0.4220
Epoch 7/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8166 - loss: 0.4231 - val_accuracy: 0.8195 - val_loss: 0.4198
Epoch 8/150
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8206 - loss: 0.4209 - val_accuracy: 0.8280

# Predicting and evaluating the model 

In [116]:
y_pred = ann.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [117]:
y_pred = (y_pred > 0.5)

In [118]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),axis = 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Accuracy Score 

In [119]:
from sklearn.metrics import accuracy_score,confusion_matrix

ac = accuracy_score(y_test,y_pred)
ac

0.845

# Confusion matrix

In [120]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[1550,   45],
       [ 265,  140]])