In [2]:
import numpy as np           # numpy is used to handle the array

In [3]:
np.__version__               # 2 under score are used for version 

'1.26.4'

In [4]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# Creating LIST 

In [6]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

# Converting list to array 

In [8]:
#! pip install numpy 

In [9]:
arr = np.array(my_list)

In [10]:
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
type(arr)

numpy.ndarray

In [12]:
type(my_list)

list

In [13]:
np.         # type np. tab to see all the functions 

SyntaxError: invalid syntax (16632163.py, line 1)

In [14]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [16]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.arange(10)                # one argument 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(10,20)               # two arguments 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [21]:
np.arange(20,10)           # first argument should be less than second arumentargument 

array([], dtype=int32)

In [22]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [23]:
np.arange()

TypeError: arange() requires stop to be specified.

In [24]:
np.arange(10,30,5)                     # 5 is the interval between the 10,30 

array([10, 15, 20, 25])

In [25]:
np,arange(10,30,5,8)             # only three agruments are applied 

NameError: name 'arange' is not defined

In [26]:
np.zeros(10)              # parameter tunning 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(10,dtype=int)       #hyperparameter tunning 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [29]:
np.zeros((2,2), dtype=int)        # two dimensions 

array([[0, 0],
       [0, 0]])

In [30]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))   

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [31]:
np.zeros((2,10))            # left side refers to the rows and right side refers to the columns 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.zeros((3,15))           # 3 rows and 10 columns 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.zeros((10,10))        # 10 rows and 10 columns 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
np.ones(3)

array([1., 1., 1.])

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [38]:
np.two((2,3))                # it is not a inbuilt function 

AttributeError: module 'numpy' has no attribute 'two'

In [39]:
np.three((2,3))

AttributeError: module 'numpy' has no attribute 'three'

In [40]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [41]:
np.random.rand(4)         # np is a package , random is and rand is a function 

array([0.91782859, 0.17650825, 0.51316171, 0.38454945])

In [42]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [43]:
np.random.rand(3,5)

array([[0.47616701, 0.77223292, 0.70109261, 0.24440064, 0.91193161],
       [0.12721735, 0.6209253 , 0.70142318, 0.62098626, 0.23540288],
       [0.6867083 , 0.93153343, 0.61928628, 0.00933494, 0.39177513]])

In [44]:
np.random.randint(4,6)            #4 and 5 print , and 6 is exclusive 

4

In [45]:
np.random.randint(2,20,4)           # 4 is to generate 4 integer between 2 to 20 

array([ 8, 15,  7, 17])

In [46]:
np.random.randint(0,1)

0

In [47]:
np.random.randint(10,20,5)

array([11, 15, 10, 19, 13])

In [48]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [49]:
np.random.randint(1)

0

In [50]:
np.random.randint(5,9)

7

In [51]:
np.random.randint(2,30)

25

In [52]:
np.random.randint(1,10,4)         # is - [6,3,9,6] or[3,2,2,5] or[6,5,5,3] and so on 

array([6, 3, 5, 9])

In [53]:
np.random.randint(1,3,5)

array([2, 2, 1, 1, 2])

In [54]:
np.random.randint(30,20,10)        # first element should be lower than nxt element 

ValueError: low >= high

In [55]:
np.random.randint(10,20,(10,10))

array([[14, 10, 13, 11, 19, 17, 11, 17, 16, 17],
       [16, 13, 15, 15, 10, 10, 14, 11, 19, 10],
       [13, 12, 16, 16, 19, 10, 16, 11, 15, 14],
       [16, 13, 10, 12, 14, 16, 14, 17, 12, 12],
       [17, 15, 19, 15, 11, 14, 14, 17, 17, 13],
       [16, 11, 11, 15, 18, 12, 11, 12, 13, 13],
       [12, 19, 12, 10, 13, 17, 13, 11, 10, 13],
       [12, 19, 15, 15, 16, 12, 17, 10, 18, 18],
       [16, 10, 17, 19, 17, 14, 18, 13, 17, 18],
       [18, 14, 18, 11, 10, 10, 12, 11, 13, 16]])

In [56]:
np.random.randint(10,40,(5,5))      # generate the elements in between -10-40in 5*5 matrix 

array([[27, 22, 11, 29, 29],
       [38, 13, 26, 24, 16],
       [13, 19, 36, 36, 10],
       [37, 32, 30, 27, 25],
       [39, 22, 32, 26, 21]])

In [57]:
b = np.random.randint(10,20,(5,4))
b

array([[18, 12, 12, 12],
       [14, 18, 16, 16],
       [13, 16, 18, 15],
       [17, 12, 17, 12],
       [17, 17, 10, 10]])

In [58]:
b[:]

array([[18, 12, 12, 12],
       [14, 18, 16, 16],
       [13, 16, 18, 15],
       [17, 12, 17, 12],
       [17, 17, 10, 10]])

In [59]:
b[0:2]

array([[18, 12, 12, 12],
       [14, 18, 16, 16]])

In [60]:
b

array([[18, 12, 12, 12],
       [14, 18, 16, 16],
       [13, 16, 18, 15],
       [17, 12, 17, 12],
       [17, 17, 10, 10]])

In [61]:
b[0:-1]

array([[18, 12, 12, 12],
       [14, 18, 16, 16],
       [13, 16, 18, 15],
       [17, 12, 17, 12]])

In [62]:
b

array([[18, 12, 12, 12],
       [14, 18, 16, 16],
       [13, 16, 18, 15],
       [17, 12, 17, 12],
       [17, 17, 10, 10]])

In [63]:
b[0,2]

12

In [64]:
a = np.ran

AttributeError: module 'numpy' has no attribute 'ran'

In [65]:
arr 

array([0, 1, 2, 3, 4, 5])

In [66]:
arr2 = np.random.randint(0,100,(10,10))

In [67]:
arr

array([0, 1, 2, 3, 4, 5])

In [68]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [69]:
arr[:4]

array([0, 1, 2, 3])

In [70]:
arr2[:]

array([[19, 37, 97, 86,  6, 18, 33, 37, 43, 98],
       [29, 62, 64, 33, 48, 90, 52, 77,  5, 14],
       [20, 67, 57, 24, 80,  2, 25, 74,  1, 36],
       [55, 50, 84, 19, 57, 96, 96, 13, 88, 78],
       [93, 91, 96, 45, 13, 51, 56, 77, 17, 35],
       [56, 63, 32, 88, 47, 37, 17,  5, 15, 36],
       [99, 91, 58, 16,  1, 43, 46, 73, 98, 68],
       [39, 15, 78, 81, 47, 67, 57, 93, 33, 27],
       [63, 53, 60, 27, 43, 43, 77, 90, 18, 94],
       [72, 51, 12, 38, 89, 57, 47, 73, 42, 67]])

In [71]:
arr2[0:5]

array([[19, 37, 97, 86,  6, 18, 33, 37, 43, 98],
       [29, 62, 64, 33, 48, 90, 52, 77,  5, 14],
       [20, 67, 57, 24, 80,  2, 25, 74,  1, 36],
       [55, 50, 84, 19, 57, 96, 96, 13, 88, 78],
       [93, 91, 96, 45, 13, 51, 56, 77, 17, 35]])

In [72]:
arr2

array([[19, 37, 97, 86,  6, 18, 33, 37, 43, 98],
       [29, 62, 64, 33, 48, 90, 52, 77,  5, 14],
       [20, 67, 57, 24, 80,  2, 25, 74,  1, 36],
       [55, 50, 84, 19, 57, 96, 96, 13, 88, 78],
       [93, 91, 96, 45, 13, 51, 56, 77, 17, 35],
       [56, 63, 32, 88, 47, 37, 17,  5, 15, 36],
       [99, 91, 58, 16,  1, 43, 46, 73, 98, 68],
       [39, 15, 78, 81, 47, 67, 57, 93, 33, 27],
       [63, 53, 60, 27, 43, 43, 77, 90, 18, 94],
       [72, 51, 12, 38, 89, 57, 47, 73, 42, 67]])

In [73]:
arr2[1,5]

90

In [74]:
arr2

array([[19, 37, 97, 86,  6, 18, 33, 37, 43, 98],
       [29, 62, 64, 33, 48, 90, 52, 77,  5, 14],
       [20, 67, 57, 24, 80,  2, 25, 74,  1, 36],
       [55, 50, 84, 19, 57, 96, 96, 13, 88, 78],
       [93, 91, 96, 45, 13, 51, 56, 77, 17, 35],
       [56, 63, 32, 88, 47, 37, 17,  5, 15, 36],
       [99, 91, 58, 16,  1, 43, 46, 73, 98, 68],
       [39, 15, 78, 81, 47, 67, 57, 93, 33, 27],
       [63, 53, 60, 27, 43, 43, 77, 90, 18, 94],
       [72, 51, 12, 38, 89, 57, 47, 73, 42, 67]])

In [75]:
arr2[-5,5]

37

In [76]:
arr2[-5,-5]

37

In [77]:
arr2

array([[19, 37, 97, 86,  6, 18, 33, 37, 43, 98],
       [29, 62, 64, 33, 48, 90, 52, 77,  5, 14],
       [20, 67, 57, 24, 80,  2, 25, 74,  1, 36],
       [55, 50, 84, 19, 57, 96, 96, 13, 88, 78],
       [93, 91, 96, 45, 13, 51, 56, 77, 17, 35],
       [56, 63, 32, 88, 47, 37, 17,  5, 15, 36],
       [99, 91, 58, 16,  1, 43, 46, 73, 98, 68],
       [39, 15, 78, 81, 47, 67, 57, 93, 33, 27],
       [63, 53, 60, 27, 43, 43, 77, 90, 18, 94],
       [72, 51, 12, 38, 89, 57, 47, 73, 42, 67]])

In [78]:
arr2[-1,-2]

42

In [79]:
arr2

array([[19, 37, 97, 86,  6, 18, 33, 37, 43, 98],
       [29, 62, 64, 33, 48, 90, 52, 77,  5, 14],
       [20, 67, 57, 24, 80,  2, 25, 74,  1, 36],
       [55, 50, 84, 19, 57, 96, 96, 13, 88, 78],
       [93, 91, 96, 45, 13, 51, 56, 77, 17, 35],
       [56, 63, 32, 88, 47, 37, 17,  5, 15, 36],
       [99, 91, 58, 16,  1, 43, 46, 73, 98, 68],
       [39, 15, 78, 81, 47, 67, 57, 93, 33, 27],
       [63, 53, 60, 27, 43, 43, 77, 90, 18, 94],
       [72, 51, 12, 38, 89, 57, 47, 73, 42, 67]])

In [80]:
arr2[::-1]

array([[72, 51, 12, 38, 89, 57, 47, 73, 42, 67],
       [63, 53, 60, 27, 43, 43, 77, 90, 18, 94],
       [39, 15, 78, 81, 47, 67, 57, 93, 33, 27],
       [99, 91, 58, 16,  1, 43, 46, 73, 98, 68],
       [56, 63, 32, 88, 47, 37, 17,  5, 15, 36],
       [93, 91, 96, 45, 13, 51, 56, 77, 17, 35],
       [55, 50, 84, 19, 57, 96, 96, 13, 88, 78],
       [20, 67, 57, 24, 80,  2, 25, 74,  1, 36],
       [29, 62, 64, 33, 48, 90, 52, 77,  5, 14],
       [19, 37, 97, 86,  6, 18, 33, 37, 43, 98]])

In [81]:
arr2

array([[19, 37, 97, 86,  6, 18, 33, 37, 43, 98],
       [29, 62, 64, 33, 48, 90, 52, 77,  5, 14],
       [20, 67, 57, 24, 80,  2, 25, 74,  1, 36],
       [55, 50, 84, 19, 57, 96, 96, 13, 88, 78],
       [93, 91, 96, 45, 13, 51, 56, 77, 17, 35],
       [56, 63, 32, 88, 47, 37, 17,  5, 15, 36],
       [99, 91, 58, 16,  1, 43, 46, 73, 98, 68],
       [39, 15, 78, 81, 47, 67, 57, 93, 33, 27],
       [63, 53, 60, 27, 43, 43, 77, 90, 18, 94],
       [72, 51, 12, 38, 89, 57, 47, 73, 42, 67]])

In [82]:
arr2[::-2]

array([[72, 51, 12, 38, 89, 57, 47, 73, 42, 67],
       [39, 15, 78, 81, 47, 67, 57, 93, 33, 27],
       [56, 63, 32, 88, 47, 37, 17,  5, 15, 36],
       [55, 50, 84, 19, 57, 96, 96, 13, 88, 78],
       [29, 62, 64, 33, 48, 90, 52, 77,  5, 14]])

In [83]:
arr2

array([[19, 37, 97, 86,  6, 18, 33, 37, 43, 98],
       [29, 62, 64, 33, 48, 90, 52, 77,  5, 14],
       [20, 67, 57, 24, 80,  2, 25, 74,  1, 36],
       [55, 50, 84, 19, 57, 96, 96, 13, 88, 78],
       [93, 91, 96, 45, 13, 51, 56, 77, 17, 35],
       [56, 63, 32, 88, 47, 37, 17,  5, 15, 36],
       [99, 91, 58, 16,  1, 43, 46, 73, 98, 68],
       [39, 15, 78, 81, 47, 67, 57, 93, 33, 27],
       [63, 53, 60, 27, 43, 43, 77, 90, 18, 94],
       [72, 51, 12, 38, 89, 57, 47, 73, 42, 67]])

In [84]:
arr2[::-3]

array([[72, 51, 12, 38, 89, 57, 47, 73, 42, 67],
       [99, 91, 58, 16,  1, 43, 46, 73, 98, 68],
       [55, 50, 84, 19, 57, 96, 96, 13, 88, 78],
       [19, 37, 97, 86,  6, 18, 33, 37, 43, 98]])

In [85]:
arr

array([0, 1, 2, 3, 4, 5])

In [86]:
arr.max()                   # print the maximum value from the array  

5

In [87]:
arr.min()                  # print the minimum value from the array 

0

In [88]:
arr                       # print the over alll elements in the array 

array([0, 1, 2, 3, 4, 5])

In [89]:
arr.mean()             # print the mean of the elements in the array (adding the all elements) 

2.5

In [90]:
arr.median()         # median is not an attribute 

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [91]:
>>> from numpy import*
>>> a = array([1,2,3,4,9])
>>> median(a)

3.0

In [92]:
arr 

array([0, 1, 2, 3, 4, 5])

In [93]:
arr.reshape(2,3)           # reshape is used to reshape in the elements in array (in another dimensions 2 rows and 3clounms)

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [95]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [96]:
mat = np.arange(0,100).reshape(10,10)

In [97]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [98]:
row = 4
col = 5

In [99]:
col

5

In [100]:
row

4

In [101]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [102]:
mat[row,col]

45

In [103]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [104]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [105]:
col = 6

In [106]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# with slices

In [107]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [108]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [109]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [110]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [112]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [113]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [114]:
row

4

In [115]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [116]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [117]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [118]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [119]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [120]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [121]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [122]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [123]:
row

4

In [124]:
col

6

In [125]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

mat

In [126]:
mat[1,4]           # 1= row , 4=column

14

In [127]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [128]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [129]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [131]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [132]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [133]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [137]:
print(mat[6])
print(mat[8])

[60 61 62 63 64 65 66 67 68 69]
[80 81 82 83 84 85 86 87 88 89]


In [138]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [139]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [140]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [141]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [142]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [143]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [144]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [145]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [146]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [148]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [149]:
mat[::-1]                  # array in the reverse order 

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [150]:
mat[::-2]             # printing the array by interval(gap) of two 

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [151]:
mat[::-3]          # printing the array by interval(gap) of three

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [152]:
mat[::-5]       # printing the array by interval(gap) of five

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [153]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [154]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [155]:
mat[0,1]

1

In [156]:
mat[1,6]

16

In [157]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [158]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [159]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [160]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [161]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [162]:
mat[3,5]

35

In [164]:
mat[1:2,2:4,4:6]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [165]:
mat[2:3,4:5]

array([[24]])

In [166]:
mat    # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [167]:
id(mat)

1697080927952

In [168]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [169]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [170]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [171]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [172]:
mat[mat==50]

array([50])

In [174]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [175]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [177]:
a2 = mat[mat>50]
a2                         # above 50 all array elements are printed 

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [178]:
a3 = mat[mat>=50]
a3                  # print the array from equal and above the 50 

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [180]:
a4 = mat[mat==50]
a4

array([50])

In [181]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [182]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [183]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [184]:
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [185]:
a4

array([50])